spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/article?currentSchema=public&characterEncoding=UTF-8 
    username: hoon
    password: qwer1234!Q
    driver-class-name: org.postgresql.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hoon.article.entity
  configuration:
    map-underscore-to-camel-case: true
    
logging:
  level:
    com.hoon.article.mapper: trace